# Generated by Django 5.0 on 2025-02-08 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_customer_order_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="name",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="review",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                default=1,  # Replace with a valid Movie ID
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=1,  # Replace with a valid User ID
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
